EMall/EMall.net/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMall.net.Models;
using EMallDataAccess.DataAccess;
using EMallDataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EMall.net.Controllers
{
    public class UserController : Controller
    {
        [BindProperty]
        public new EMall.net.Models.Buyer User { get; set; }
        public ActionResult BuyerRegister()
        {
            User = new EMall.net.Models.Buyer();
            
            return View(User);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BuyerRegisterPost()
        {
            

                //_db.Users.Add(User);

                //_db.SaveChanges();
                EMallDataAccess.Models.User UserDB = new EMallDataAccess.Models.User{ Username = User.Username, Email = User.Email, Password = User.Password, UserType=UserType.Buyer, RegisterTime = DateTime.Now };
                UserOperator.Single.Add(UserDB);
                return RedirectToAction("BuyerLogin");
            
        }
        public ActionResult BuyerLogin()
        {
            User = new EMall.net.Models.Buyer();

            return View(User);
        }

        public ActionResult BuyerLoginPost()
        {
            //if (ModelState.IsValid)
            //{
            // UserDB = _db.Users.FirstOrDefault(u => u.Username == Username);
            // 
            EMallDataAccess.Models.User UserDB = UserOperator.Single.Login(User.Username, User.Password, UserType.Buyer);
                if (UserDB == null)
                {
                    return RedirectToAction("BuyerLogin");
                }
                
                /*if (User.Password != UserDB.Password)
                {
                    return RedirectToAction("BuyerLogin");
                }*/
                
            HttpContext.Session.SetString("UserName",User.Username);
            HttpContext.Session.SetInt32("UserId", UserDB.ID);
            HttpContext.Session.SetString("Name", UserDB.FirstName+" " +UserDB.LastName);
            HttpContext.Session.SetString("Address", UserDB.Address);
            HttpContext.Session.SetString("City", UserDB.City);
            HttpContext.Session.SetString("Province", UserDB.Province);
            HttpContext.Session.SetString("PostalCode", UserDB.PostalCode);
            HttpContext.Session.SetString("Email", UserDB.Email);
            HttpContext.Session.SetString("PhoneNo", UserDB.PhoneNo);
            return RedirectToAction("Index","Home");
            //}
            //return RedirectToAction("/Home/Index");
        }

        public ActionResult BuyerLogOut()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        /*[HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var bookFromDb = await _db.Books.FirstOrDefaultAsync(u => u.Id == id);
            if (bookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Books.Remove(bookFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }*/
        //#endregion

    }
}

EMall/EMall.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMall.net</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMall.net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <!--li class="nav-item">
                            <a class="nav-link text-dark" style="display:inline-block" asp-area="" asp-controller="User" asp-action="BuyerRegister">Register</a> /
                            <a class="nav-link text-dark" style="display:inline-block" asp-area="" asp-controller="User" asp-action="BuyerLogin">Login</a>
                        </!li-->

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EMall.net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EMall/EMall.net/Views/Shared/_SellerLayout.cshtml
@model EMall.net.Models.SellerModelBase
<!DOCTYPE html>
<html>
<head>
    <!-- Css Styles -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMall Sellersd</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/emall.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header class="emall-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">

            <div class="col-8 text-center">
                <a class="emall-header-logo text-dark" href="#">E-Mall Sellers</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                @if (Model.Seller == null)
                {
                    <a class="btn btn-sm btn-outline-secondary" href='/seller/login' target='_self'>Login</a> <a class="btn btn-sm btn-outline-secondary" href='/seller/register' target='_self'>Register</a>
                }
                else
                {
                    <p>Welcome back  <b>@Model.Seller.FullName</b>. <a class="btn btn-sm btn-outline-secondary" href='/seller/logout' target='_self'>Logout</a></p>
                }


            </div>
        </div>

    </header>

    <!--header-->
    @if (Model.Seller != null)
    {
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a id="menuDashboard" class="nav-link" asp-area="" asp-controller="Seller" asp-action="Index">
                                    <span data-feather="home"></span>
                                    Dashboard <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a id="menuPersonal" class="nav-link" asp-area="" asp-controller="Seller" asp-action="PersonalSetting">
                                    <span data-feather="users"></span>
                                    Personal Setting
                                </a>
                            </li>

                            <li class="nav-item">
                                <a id="menuProducts" class="nav-link" asp-area="" asp-controller="Seller" asp-action="Product">
                                    <span data-feather="grid"></span>
                                    My Products
                                </a>
                            </li>
                            <li class="nav-item">
                                <a id="menuOrderInprocess" class="nav-link" asp-area="" asp-controller="Seller" asp-action="OrderInProcess">
                                    <span data-feather="file-plus"></span>
                                    Orders Inprocess
                                </a>
                            </li>
                            <li class="nav-item">
                                <a id="menuOrderHistory" class="nav-link" asp-area="" asp-controller="Seller" asp-action="OrderHistory">
                                    <span data-feather="file-text"></span>
                                    Orders History
                                </a>
                            </li>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Sales Performance</span>
                            <a class="d-flex align-items-center text-muted" asp-area="" asp-controller="Seller" asp-action="SalePerformance">
                                <span data-feather="plus-circle"></span>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-2">
                            <li class="nav-item">
                                <a id="menuPerformanceMonth" class="nav-link" asp-controller="Seller" asp-action="SalePerformance" asp-route-period="month">
                                    <span data-feather="file-text"></span>
                                    Current month
                                </a>
                            </li>
                            <li class="nav-item">
                                <a id="menuPerformanceQuarter" class="nav-link" asp-controller="Seller" asp-action="SalePerformance" asp-route-period="quarter">
                                    <span data-feather="file-text"></span>
                                    Current quarter
                                </a>
                            </li>

                            <li class="nav-item">
                                <a id="menuPerformanceYear" class="nav-link" asp-controller="Seller" asp-action="SalePerformance" asp-route-period="year">
                                    <span data-feather="file-text"></span>
                                    This Year
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    @RenderBody()
                </main>
            </div>
        </div>

    }
    else
    {
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <P>
                    Here is an advertisement for sellers.
                    Welcome to E-Mall Sellers, <a class="btn btn-sm btn-outline-secondary" href='/seller/register' target='_self'>Register</a> to begin your business.
                </P>
                @RenderBody()
            </main>
    }

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2020 - EMall.net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>

            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
            </environment>
            <environment exclude="Development">
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
                </script>
            </environment>
            <script src="~/js/site.js" asp-append-version="true"></script>

            @RenderSection("Scripts", required: false)
    </body>

</html>